[package]
name = "aimee_api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
url.workspace = true
async-trait.workspace = true
aimee_domain.workspace = true
aimee_stream.workspace = true
aimee_services.workspace = true
aimee_repo.workspace = true
aimee_infra.workspace = true
futures.workspace = true








aimee_app.workspace = true
serde_json.workspace = true
aimee_config.workspace = true

[dev-dependencies]

tokio = { workspace = true }


